name: Release TVGate

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
          - linux-armv7
          - linux-386
          - linux-ppc64
          - linux-ppc64le
          - linux-s390x
          - windows-amd64
          - windows-386
          - darwin-amd64
          - darwin-arm64
          - android-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: stable

      - name: Install cross-compilers
        run: |
          set -e
          case "${{ matrix.platform }}" in
            linux-arm64) sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu ;;
            linux-armv7) sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf ;;
            linux-armv6) sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf ;;
            linux-386)   sudo apt-get update && sudo apt-get install -y gcc-i686-linux-gnu ;;
            linux-armv5) sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabi ;;
            linux-s390x) sudo apt-get update && sudo apt-get install -y gcc-s390x-linux-gnu ;;
          esac

      - name: Set environment variables
        run: |
          export VERSION=$(cat config/version 2>/dev/null || echo "latest")
          export CGO_ENABLED=0
          case "${{ matrix.platform }}" in
            linux-amd64)  export GOOS=linux; export GOARCH=amd64 ;;
            linux-arm64)  export GOOS=linux; export GOARCH=arm64; export CC=aarch64-linux-gnu-gcc; export CGO_ENABLED=1 ;;
            linux-armv7)  export GOOS=linux; export GOARCH=arm; export GOARM=7; export CC=arm-linux-gnueabihf-gcc; export CGO_ENABLED=1 ;;
            linux-armv6)  export GOOS=linux; export GOARCH=arm; export GOARM=6; export CC=arm-linux-gnueabihf-gcc; export CGO_ENABLED=1 ;;
            linux-386)    export GOOS=linux; export GOARCH=386; export CC=i686-linux-gnu-gcc; export CGO_ENABLED=1 ;;
            linux-armv5)  export GOOS=linux; export GOARCH=arm; export GOARM=5; export CC=arm-linux-gnueabi-gcc; export CGO_ENABLED=1 ;;
            linux-s390x)  export GOOS=linux; export GOARCH=s390x; export CC=s390x-linux-gnu-gcc; export CGO_ENABLED=1 ;;
            windows-amd64) export GOOS=windows; export GOARCH=amd64 ;;
            windows-386)   export GOOS=windows; export GOARCH=386 ;;
            darwin-amd64)  export GOOS=darwin; export GOARCH=amd64 ;;
            darwin-arm64)  export GOOS=darwin; export GOARCH=arm64 ;;
            android-arm64) export GOOS=android; export GOARCH=arm64 ;;
          esac

      - name: Build TVGate
        run: |
          mkdir -p build
          OUTPUT="build/TVGate-${GOOS}-${GOARCH}"
          [ "$GOOS" = "windows" ] && OUTPUT="$OUTPUT.exe"
          LDFLAGS="-s -w -extldflags '-static' -X 'github.com/qist/tvgate/config.Version=$VERSION'"
          go build -ldflags="$LDFLAGS" -o $OUTPUT .

      - name: Prepare packaging
        run: |
          mkdir -p package
          cp README.md package/
          cp doc/config.yaml package/
          if [[ "$GOOS" == "windows" ]]; then
            cp build/TVGate-windows-${GOARCH}.exe package/
          else
            cp build/TVGate-${GOOS}-${GOARCH} package/
            cp TVGate.service package/
          fi

      - name: Package
        run: |
          cd package
          if [[ "$GOOS" == "windows" ]]; then
            zip -r "../TVGate-${GOOS}-${GOARCH}.zip" *
          else
            tar -czvf "../TVGate-${GOOS}-${GOARCH}.tar.gz" *
          fi
          cd ..

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: |
            build/TVGate-*.tar.gz
            build/TVGate-*.zip
          overwrite: true
