name: Release TVGate

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux-amd64
          - linux-arm64
          - linux-armv7
          - linux-386
          - linux-ppc64
          - linux-ppc64le
          - linux-s390x
          - windows-amd64
          - windows-386
          - darwin-amd64
          - darwin-arm64
          - android-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: stable

      - name: Set environment variables
        run: |
          VERSION=$(cat config/version 2>/dev/null || echo "latest")
          export VERSION
          export CGO_ENABLED=0
          case "${{ matrix.platform }}" in
            linux-amd64)  export GOOS=linux; export GOARCH=amd64 ;;
            linux-arm64)  export GOOS=linux; export GOARCH=arm64 ;;
            linux-armv7)  export GOOS=linux; export GOARCH=arm; export GOARM=7 ;;
            linux-386)    export GOOS=linux; export GOARCH=386 ;;
            linux-ppc64)  export GOOS=linux; export GOARCH=ppc64 ;;
            linux-ppc64le) export GOOS=linux; export GOARCH=ppc64le ;;
            linux-s390x)  export GOOS=linux; export GOARCH=s390x ;;
            windows-amd64) export GOOS=windows; export GOARCH=amd64 ;;
            windows-386)   export GOOS=windows; export GOARCH=386 ;;
            darwin-amd64)  export GOOS=darwin; export GOARCH=amd64 ;;
            darwin-arm64)  export GOOS=darwin; export GOARCH=arm64 ;;
            android-arm64) export GOOS=android; export GOARCH=arm64 ;;
          esac

      - name: Build TVGate
        run: |
          mkdir -p build
          OUTPUT="build/TVGate-${GOOS}-${GOARCH}"
          [ "$GOOS" = "windows" ] && OUTPUT="$OUTPUT.exe"
          LDFLAGS="-s -w -X 'github.com/qist/tvgate/config.Version=$VERSION'"
          go build -ldflags="$LDFLAGS" -o $OUTPUT .

      - name: Prepare packaging
        run: |
          mkdir -p package
          cp README.md package/
          cp doc/config.yaml package/
          if [[ "$GOOS" == "windows" ]]; then
            cp build/TVGate-windows-${GOARCH}.exe package/
          else
            cp build/TVGate-${GOOS}-${GOARCH} package/
            cp doc/TVGate.service package/
          fi

      - name: Package
        run: |
          cd package
          if [[ "$GOOS" == "windows" ]]; then
            zip -r "../TVGate-${GOOS}-${GOARCH}.zip" *
          else
            tar -czvf "../TVGate-${GOOS}-${GOARCH}.tar.gz" *
          fi
          cd ..

      - name: Upload files to GH release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: |
            build/TVGate-*.tar.gz
            build/TVGate-*.zip
          prerelease: true
          overwrite: true
      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v5
